name: Python CI

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**' # Triggers on PR creation, updates, or reopening against any branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'
    - name: Install dependencies
      run: |
        cd software/python
        pip install -e .
    - name: Install linters and formatters
      run: |
        pip install black==24.10.0 flake8==7.0.0
    - name: Run Black formatter
      run: |
        cd software/python
        black --check --skip-magic-trailing-comma .
    - name: Run tests
      run: |
        cd software/python
        pip install pytest==8.1.1 pytest-cov==5.0.0
        python3 -m pytest -v --cov --disable-warnings tests/
        flake8 --statistics
