name: Python CI

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**' # Triggers on PR creation, updates, or reopening against any branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'
    - name: Install dependencies
      run: |
        pip install -r software/python/requirements.txt
    - name: Run tests
      run: |
        cd software/python
        pip install flake8==7.0.0 pytest==8.1.1 pytest-cov==5.0.0
        python3 -m pytest -v --cov tests/
        flake8 --statistics
